pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('install') {
            steps {
                sh 'cd vite-project'
                sh 'npm install'
            }
        }
        stage('build') {
            steps {
                sh 'cd vite-project'
                sh 'npm run build'
            }
        }
    }
}