pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('install') {
            steps {
                sh './VITE-PROJECT/npm install'
            }
        }
        stage('build') {
            steps {
                sh './VITE-PROJECTnpm run build'
            }
        }
    }
}