pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('install') {
            steps {
                sh 'vite-project/npm install'
            }
        }
        stage('build') {
            steps {
                sh 'vite-project/npm run build'
            }
        }
    }
}